modules/inception/gcp/bastion-startup.tmpl
This will always run `gcloud auth revoke` on the exit of SSH.
=> feat: revoke gcloud creds on exit

modules/inception/gcp/bastion-startup.tmpl, modules/inception/gcp/bastion.tf, modules/inception/gcp/variables.tf
Adds optional `bastion_revoke_on_exit` variable to set whether or not we are revoking credential on exiting ssh tunnel to bastion
=> chore: revoke credential on bastion setting exposed to variables

examples/gcp/README.md
Adding bastion as true as it follows with the rest of the example. 
P.S. Please let me know if there are any specific PR standards I need to follow for this change to go through. #newbie
=> docs: Update Example, bastion is a required attribute in variable users.

modules/platform/gcp/cloud-sql.tf, modules/platform/gcp/outputs.tf, modules/platform/gcp/variables.tf
We need dedicated PostgreSQL Cloud SQL instance for LND.
Related: https://github.com/GaloyMoney/charts/pull/1012
=> feat: cloud sql instance for lnd

modules/inception/gcp/platform-roles.tf
opened in place of https://github.com/GaloyMoney/galoy-deployments/pull/1701
=> fix: add monitoring access to platform users

modules/inception/gcp/bastion-startup.tmpl
bitcoin.org is blocked in the UK due to legal proceedings involving the site owner
bitcoincore.org has a different ownership and therefore a more reliable source
Test:
https://bitcoin.org/bin/bitcoin-core-22.0/
leads to a 404 error froma  UK IP address
https://bitcoincore.org/bin/bitcoin-core-22.0/
is available from everywhere
=> fix: link to bitcoin binary

modules/inception/gcp/platform-roles.tf
add permission to action: https://github.com/GaloyMoney/galoy-infra/pull/56
https://cloud.google.com/sql/docs/postgres/flags
fixing: https://ci.galoy.io/teams/galoy/pipelines/galoy-deployments/jobs/galoy-bbw-platform/builds/55
=> fix: add permission to edit postgresql settings

modules/inception/gcp/nat.tf
Looks like without external IP on the VPC, to give Internet access to the bastion (which lets the startup script run properly) we need the NAT. 
https://serverfault.com/questions/947970/google-compute-engine-trouble-accessing-internet-from-an-instance-without-exter
Moved the NAT from platform to inception.
Tested locally and working!
My assumption is there was some race condition between GCE running the startup script and platform applying the NAT which is why on the CI it was not reliably failing?
=> fix!: bastion internet access needs nat

modules/inception/gcp/bastion-startup.tmpl
Since we already add the hashicorp repo, vault should be available to install without any other changes.
=> chore: add vault to bastion startup script

ci/tasks/check-and-upgrade-k8s.sh
hcledit expects the argument to be enquoted, otherwise it errors
=> fix: enquote param to hcledit

modules/inception/gcp/bastion-startup.tmpl
`gcloud components install gke-gcloud-auth-plugin` returns the following error:
```
ERROR: (gcloud.components.install) You cannot perform this action because this Google Cloud CLI installation is managed by an external package manager.
Please consider using a separate installation of the Google Cloud CLI created through the default mechanism described at: https://cloud.google.com/sdk/
```
We'll have to install it from apt instead
=> fix: switch to installing gke auth plugin from apt

modules/inception/gcp/bastion-startup.tmpl
Fixing the errors seen when logging in to the bastions:
- bos completion needs to be sourced, not displayed
- the error needing the `gke-gcloud-auth-plugin` is displayed when running: `kauth`:
```
openoms_galoy_io@galoy-staging-bastion:~$ kauth
Fetching cluster endpoint and auth data.
CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
kubeconfig entry generated for galoy-staging-cluster.
```
this needs to be installed with apt
=> Fix-bastion-errors

modules/services/opentelemetry-values.yml
Used the config from https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor#section-readme with some inspiration from https://github.com/newrelic-experimental/otel-workshop/blob/efc49476d66fde177cc890b89443c8b23ca706b5/src/otel-collector-agent/collector.yaml#L27
=> feat: add k8sattributes to otel tracing

modules/services/opentelemetry-values.yml
Kind of testing, but have a good feeling about this.
Following the [documentation](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor#section-readme), we need the cluster roles attached to the collector along with specifying which metadata to extract and pod_association resource attributes.
Those things have been added in this PR.
(Aside) Locally, no `k8s` data gets pushed to Honeycomb, which is strange. Maybe k3d doesn't have integrations?
=> feat: add k8sattributes in collector mode

modules/services/ingress-values.yml.tmpl
NGINX Ingress Controller upgrade for `networking.k8s.io/v1`.
https://kubernetes.github.io/ingress-nginx/#faq-migration-to-apiversion-networkingk8siov1
This PR:
- Makes this the default ingress controller for the cluster.
- Watches Ingress without class so that even if `spec.ingressClassName` is not set in `kind: Ingress`, nginx ingress controller still works for them.
=> chore: ingress class make default

ci/k8s-upgrade/main.tf
Updated CI to make sure the bumps henceforth are for K8s 1.22
=> chore!: upgrade cluster to Kubernetes 1.22

modules/platform/gcp/kube.tf
https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#available_node_images
=> fix: use containerd node pool as cos deprecated

modules/services/smoketest.tf
Reverts GaloyMoney/galoy-infra#100
The permission is granted only for the smoketest namespace, however kafka operator is incapable of watching that namespace as it's deployed to its own dedicated namespace. Hence, these permissions are never used.
=> Revert "chore: add kafkatopic permissions to smoketest svc account"

modules/smoketest/gcp/main.tf
From k8s `v1.24.0` onwards, a token for the service account is not created automatically, and so needs to be created manually.
Relevant error from provider -
```
│ Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.0 and above
│
│ Starting from version 1.24.0 Kubernetes does not automatically generate a token for service accounts, in this case, "default_secret_name" will be empty
```
=> fix: create svc acc token manually

modules/inception/gcp/bastion.tf
Using the latest LTS image:
https://github.com/GaloyMoney/galoy-infra/blob/7c8d479be46396a196675ab3829520205d1967cb/modules/inception/gcp/variables.tf#L16
```
gcloud compute images list | grep ubuntu-2204-lts
ubuntu-2204-jammy-v20230114                           ubuntu-os-cloud      ubuntu-2204-lts
```
=> chore: bastion update bitcoin, kubectl, kratos

ci/k8s-upgrade/main.tf
It looks like either gcp or the provider no longer allow `*` to be passed in as the project id.
=> fix: specify project id in k8s upgrader

ci/tasks/gcp/teardown.sh, modules/inception/gcp/inception-roles.tf
I have tested the perm by adding it to a service account, impersonating it and trying to delete the `google_service_networking_connection` resource.
=> fix: add get project perm to destroy inception

modules/inception/gcp/network.tf
The google_service_networking_connection resource deletion is happening after the iam member gets deleted, so the service account does not have the necessary permissions to execute deletion.
=> fix: networking connection resource dependency

modules/inception/gcp/bastion.tf
Not sure if `bastion.tf` is the right place for this resource to be in, or if there's a more apt location.
=> chore: enable iap audit logs

modules/platform/gcp/variables.tf
The latest on east1 is not available on central1, and the reverse is also true. So downgrading and pausing the upgrade for sometime till the latest is rolled out to all regions.
=> fix: downgrade gke to version available on all regions

ci/image/gcp/Dockerfile
Building the image with docker fails because of `netcat` package. This PR uses the `netcat-traditional` instead, which is a potential fix to the issue.
https://forums.docker.com/t/package-netcat-has-no-installation-candidate-how-to-fix-this/136541/3
=> fix: use netcat-traditional instead of netcat

examples/gcp/postgresql/main.tf, modules/postgresql/gcp/read-replica.tf
This PR addresses the issue where running the `terraform apply` command results in a failure due to the creation of `replica` and `master` in **parallel**, which caused permission errors.
=> chore: pg replica depend on master

modules/postgresql/gcp/database/main.tf, modules/postgresql/gcp/main.tf, modules/postgresql/gcp/variables.tf
This PR prepares the source postgresql database for database update using the database migration service, with a simple `upgradable` flag. Once the flag is enabled it does the following things:
- enables `cloudsql.logical_decoding` and `cloudsql.enable_pglogical` flags
- Installs `pglogical` extension for all users.
- Creates a connection profile which is required by the database migration service for migration.
**Reference**
- https://cloud.google.com/database-migration/docs/postgres/configure-source-database#cloud-sql-postgresql
- https://cloud.google.com/database-migration/docs/postgres/configure-source-database
=> feat: Conditionally prepare source instance for migration

modules/postgresql/gcp/database/main.tf, modules/postgresql/gcp/main.tf, modules/postgresql/gcp/variables.tf
This PR removes the dependency on the database admin and creates a new `migration` role which contains all the necessary permissions for setting up the database migration via the Database Migration Service.
=> feat: Use migration user instead of database admin for migration

ci/image/gcp/Dockerfile
This PR replaces `netcat-traditional` with `netcat-bsd` in `ci/image/gcp/Dockerfile`, as the former is not maintained since 1 year.
=> fix: Use netcat-bsd instead of traditional

examples/gcp/Makefile
This PR adds
```
tf state rm module.postgresql.google_sql_user.admin \
&& $(TF) destroy
```
to the teardown step which worked while doing the test on bastion.
=> fix: destroy step with targetting the admin user

modules/postgresql/gcp/main.tf, modules/postgresql/gcp/variables.tf
This PR does:
- Adds a dependency between `postgres_grant` configurations to prevent concurrent operations on a single schema, which would otherwise throw an error.
=> fix: Resolve concurrent table update issue 

docs/pg-migration-guide/README.md, examples/gcp/bin/terraform-db-swap.sh, examples/gcp/bin/terraform-state-rm.sh, examples/gcp/postgresql/main.tf, modules/postgresql/gcp/main.tf, modules/postgresql/gcp/read-replica.tf, modules/postgresql/gcp/variables.tf
This PR does the following:
1: Includes scripts to do the `terraform mv` and `terraform state rm command`
2: Ability to provision the postgres destination using one flag `prep_upgrade_as_source_db`
3: Removes a lot of unnecessary code blocks.
=> feat: Optimise postgres update strategy

ci/k8s-upgrade/main.tf, ci/tasks/check-and-upgrade-k8s.sh
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
latest_version = "1.28.13-gke.1006000"
```
=> ci: tf module to find common latest k8s version across 3 regions

modules/postgresql/gcp/variables.tf
This PR updates the destination database version from 16 to 15. According to the documentation:
> If the database version for your instance is PostgreSQL 16 or later, the default edition is Cloud SQL Enterprise Plus.
However, the current CI configuration assumes our edition is `Enterprise` resulting in a failure due to `Enterprise Plus` not recognizing the custom configuration syntax.
cc: https://cloud.google.com/sql/docs/postgres/create-instance#machine-types
=> fix: CI failing due to destination database PG16 version

ci/tasks/gcp/postgresql.sh
Added a conditional to check if tofu is present, this serves as a potential fix for https://ci.blink.sv/teams/dev/pipelines/galoy-infra/jobs/gcp-testflight-postgresql/builds/301
=> fix: Check for tofu in gcp-testflight-postgresql

modules/platform/gcp/variables.tf
The change modifies the default value of the `deploy_lnd_ips` variable from `true` to `false` in `modules/platform/gcp/variables.tf` file.
=> feat: Remove lnd from default and make it optional

modules/bootstrap/gcp/tf-state-bucket.tf
Without this, i get:
```
│ Error: googleapi: Error 412: Request violates constraint 'constraints/storage.uniformBucketLevelAccess', conditionNotMet
│ 
│   with module.bootstrap.google_storage_bucket.tf_state,
│   on .terraform/modules/bootstrap/modules/bootstrap/gcp/tf-state-bucket.tf line 1, in resource "google_storage_bucket" "tf_state":
│    1: resource "google_storage_bucket" "tf_state" {
│ 
```
This seems to be related to the way new organisations are setup by default in GCP as this contraint is coming from the org.
https://cloud.google.com/storage/docs/uniform-bucket-level-access
=> fix: add google_storage_bucket in bootstrap module

ci/k8s-upgrade/main.tf
The previous logic would break when comparing versions with different number of digits. For example 10 would be placed before 9 after sorting, meaning that 9 would be picked up as the latest version.
This PR fixes that case.
=> fix: k8s upgrade checker comparison logic
